sources:
  - name: thub_hub
    database: fivetran_database
    tables:
      - name: billing_offers
      - name: domain_events
      - name: feature_flags
      - name: feature_flags_stages
      - name: integrations
      - name: integrations_developers
      - name: integrations_installations
      - name: invoices
      - name: invoices_discounts
      - name: invoices_items
      - name: invoices_payments
      - name: migrations
      - name: oidc_providers
      - name: organizations
      - name: organizations_admins
      - name: organizations_feature_flags
      - name: organizations_locations
      - name: organizations_meta
      - name: organizations_services
      - name: partners
      - name: partners_locations
      - name: payments_charges
      - name: payments_customers
      - name: payments_customers_legacy
      - name: payments_methods
      - name: signups
      - name: subscriptions
      - name: subscriptions_applied_offers
      - name: subscriptions_discounts
      - name: subscriptions_fee_changes
      - name: subscriptions_plans
      - name: subscriptions_products
      - name: subscriptions_referrals
      - name: subscriptions_usage_credits
      - name: users
      - name: users_access
      - name: users_access_requests
      - name: users_church_passes
      - name: users_email_requests
      - name: users_invitations
      - name: users_services
      - name: users_sessions
      - name: users_team_groups